export const langCodes = {
  en: 'English',
  ja: 'Japanese',
  es: 'Spanish',
  it: 'Italian',
  fr: 'French',
  ko: 'Korean',
  zh: 'Chinese',
  cn: 'Chinese',
  ru: 'Russian',
  uk: 'Ukrainian',
  no: 'Norwegian',
  bn: 'Bengali',
  ta: 'Tamil',
  hi: 'Hindi',
  ml: 'Malayalam',
  de: 'German',
  pt: 'Portuguese',
  th: 'Thai',
};
